api:
  platform: Mobivia
  idp-admin-role: service_identity_provider_administrator
  organizationId: mobivia
  organizationName: Mobivia
  contractAddress: KT1HtPSz6rg7PhXHN9Pjp5rpqQA3e8AzRdpf
spring:
  rabbitmq:
    port: 6672
  datasource:
    url: jdbc:postgresql://localhost:15432/collaborate
  mail:
    port: 11025
  security:
    oauth2:
      client:
        provider:
          collaborate:
            authorization-uri: http://localhost:18080/auth/realms/collaborate/protocol/openid-connect/auth
            token-uri: http://localhost:18080/auth/realms/collaborate/protocol/openid-connect/token
server:
  port: 17772
  error:
    include-message: always
  servlet:
    context-path: /api/v1

keycloak-admin-client-properties:
  base-url: http://localhost:18080/auth

keycloak:
  auth-server-url: http://localhost:18080/auth

springdoc:
  oAuthFlow:
    authorizationUrl: http://localhost:18080/auth/realms/collaborate/protocol/openid-connect/auth
    tokenUrl: http://localhost:18080/auth/realms/collaborate/protocol/openid-connect/token