api:
  platform: PSA
  idp-admin-role: service_identity_provider_administrator
  organizationId: psa
  organizationName: PSA Groupe
  contractAddress: KT1HtPSz6rg7PhXHN9Pjp5rpqQA3e8AzRdpf
  organizations:
    psa:
      id: psa
      name: PSA Groupe
      publicKeyHash: tz1W1Wu7otQ63uLPh6vdvA3j1DUHQCVJuWKa
    mobivia:
      id: mobivia
      name: Mobivia
      publicKeyHash: tz1RDUgUKrhQw3FuSXtBt2RmWbzYAP7TiWhx
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/collaborate
    username: postgres
    password: randompwd
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
      addressFrom: noreply@theblockchainxdev.com
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          catalog:
            client-id: psa
            client-secret: 57936b16-2f90-434a-9eb4-843668a3a521
            authorization-grant-type: client_credentials
          collaborate:
            client-id: collaborate-backend
            client-secret: 572255bd-1504-4d51-8389-967d8cc668f8
            authorization-grant-type: client_credentials
        provider:
          catalog:
            authorization-uri: http://localhost:10080/auth/realms/catalog/protocol/openid-connect/auth
            token-uri: http://localhost:10080/auth/realms/catalog/protocol/openid-connect/token
          collaborate:
            authorization-uri: http://localhost:8080/auth/realms/collaborate/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/collaborate/protocol/openid-connect/token
server:
  port: 7772
  error:
    include-message: always
  servlet:
    context-path: /api/v1

keycloak-admin-client-properties:
  base-url: http://localhost:8080/auth
  realm: collaborate
  user:
  password:
  client-id: collaborate-backend
  client-secret: 572255bd-1504-4d51-8389-967d8cc668f8
  grant-type: client_credentials
  verify-hostname: false

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: collaborate
  resource: collaborate-backend
  public-client: true
  bearer-only: true
  disable-trust-manager: true

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    oauth:
      clientId: collaborate-backend
      useBasicAuthenticationWithAccessCodeGrant: true
  oAuthFlow:
    authorizationUrl: http://localhost:8080/auth/realms/collaborate/protocol/openid-connect/auth
    tokenUrl: http://localhost:8080/auth/realms/collaborate/protocol/openid-connect/token

feign:
  httpclient:
    disableSslValidation: true
    enabled: false
  okhttp.enabled: true