apiVersion: v1
kind: Service
metadata:
  name: {{ include "collaborate-dapp.fullname" . }}-iam
  labels:
    {{- include "collaborate-dapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: iam
spec:
  type: {{ .Values.iam.service.type }}
  ports:
    - port: {{ .Values.iam.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "collaborate-dapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: iam
