api-properties:
  platform: PSA
  idp-admin-role: service_identity_provider_administrator
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/collaborate
    username: postgres
    password: randompwd
server:
  port: 7772

mail:
  host: localhost
  port: 1025
  username:
  password:
  properties:
    addressFrom: noreply@theblockchainxdev.com
    mail:
      smtp:
        auth: false
keycloak-admin-client-properties:
  base-url: http://localhost:8080/auth
  realm: collaborate
  user:
  password:
  client-id: collaborate-backend
  client-secret: 572255bd-1504-4d51-8389-967d8cc668f8
  grant-type: client_credentials
  verify-hostname: false

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: collaborate
  resource: collaborate-backend
  public-client: true
  bearer-only: true
  disable-trust-manager: true

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    oauth:
      clientId: collaborate-backend
      useBasicAuthenticationWithAccessCodeGrant: true
  oAuthFlow:
    authorizationUrl: http://localhost:8080/auth/realms/collaborate/protocol/openid-connect/auth
    tokenUrl: http://localhost:8080/auth/realms/collaborate/protocol/openid-connect/token

feign:
  httpclient:
    disableSslValidation: true
    enabled: false
  okhttp.enabled: true