apiVersion: v1
kind: Service
metadata:
  name: {{ include "collaborate-dapp.fullname" . }}-ipfs-gtw
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "collaborate-dapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
spec:
  type: {{ .Values.ipfs.service.gtw.type }}
  ports:
    - port: {{ .Values.ipfs.service.gtw.port }}
      targetPort: 8080
      protocol: TCP
      name: swarm
  {{- if .Values.ipfs.service.gtw.ipAddress }}
  loadBalancerIP: {{ .Values.ipfs.service.gtw.ipAddress | quote }}
  {{- end }}
  selector:
    {{- include "collaborate-dapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
