apiVersion: v1
kind: Service
metadata:
  name: {{ include "collaborate-dapp.fullname" . }}-ipfs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "collaborate-dapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
spec:
  type: {{ .Values.ipfs.service.type }}
  ports:
    - port: 4001
      targetPort: 4001
      protocol: TCP
      name: swarm
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: api
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: gtw
  selector:
    {{- include "collaborate-dapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
