api:
  ingress:
    enabled: true
    certManager: true
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: collaborate-catalog
      cert-manager.io/common-name: catalog.collaborate.localhost
    hosts:
      - host: catalog.collaborate.localhost
        paths:
          - path: "/api"

  rabbitmq:
    auth:
      password: randompwd

  mongodb:
    auth:
      password: root

  iam:
    catalog:
      uri: https://catalog.collaborate.localhost

iam:
  ingress:
    enabled: true
    certManager: true
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: collaborate-catalog
      cert-manager.io/common-name: catalog.collaborate.localhost
    hosts:
      - host: catalog.collaborate.localhost
        paths:
          - path: "/auth"
    tls:
      - secretName: catalog.collaborate.localhost-tls
        hosts:
          - catalog.collaborate.localhost

  password: kcadmin

  smtp:
    host: maildev
    auth: false
    ssl: false

  clientSecretPsa: 57936b16-2f90-434a-9eb4-843668a3a521
  clientSecretMobivia: df6935e3-2816-4d02-9d65-16cd28b8adbe

iam-db:
  postgresqlPassword: randompwd

rabbitmq:
  ingress:
    enabled: true
    certManager: true
    tls: true
    hostname: rabbitmq.catalog.collaborate.localhost
    annotations:
      cert-manager.io/cluster-issuer: collaborate-catalog
      cert-manager.io/common-name: rabbitmq.catalog.collaborate.localhost
  auth:
    password: randompwd

mongodb:
  auth:
    password: root
    rootPassword: root