api:
  rabbitmq:
    auth:
      password: randompwd

  mongodb:
    auth:
      password: root

iam:
  password: kcadmin

  smtp:
    host: maildev
    auth: false
    ssl: false

  clientSecretPsa: 57936b16-2f90-434a-9eb4-843668a3a521
  clientSecretMobivia: df6935e3-2816-4d02-9d65-16cd28b8adbe

iam-db:
  postgresqlPassword: randompwd

rabbitmq:
  ingress:
    hostname: rabbitmq.catalog.collaborate.localhost
    annotations:
      cert-manager.io/common-name: rabbitmq.catalog.collaborate.localhost
  auth:
    password: randompwd

mongodb:
  auth:
    password: root
    rootPassword: root