{{- if .Values.api.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "collaborate.fullname" . }}-ipfs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "collaborate.labels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
spec:
  podSelector:
    matchLabels:
      {{- include "collaborate.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ipfs
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{ include "collaborate.fullname" . }}-ipfs-client: "true"
{{- end }}
