apiVersion: v1
kind: Secret
metadata:
  name: {{ include "collaborate.fullname" . }}-traefik-extra-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "collaborate.labels" . | nindent 4 }}
type: Opaque
data:
  TRAEFIK_PILOT_TOKEN: {{ .Values.api.traefik.pilot.token | b64enc | quote }}
