global:
  dev: true

ingress:
  enabled: true
  host: "col.localhost"

mail:
  dev: true

api:
  platform: DSPConsortium1
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDMSL4kM7GH4Q24Z+XuGkaVGn+JLAbsvZnWlGF9O3i8MCqL9s3ZP8GGPMyFhmtgtBeLcK9gLdY4aoqP3geLdKBiqQRnVzUyKETj7ts34OsJHXVgi0JU8vY5pz32Y7/cyrExqMf+Z8kAhlzLw/kTLqEUucZt21bq9ddzbkEuGgmhYvGCSHkj8O8ErinTN/CpFSiQSzLkVyd3LzUNlRwaeoiFovtjjxJ2F70re0R1lahABVkiCWhkDF9oUivJg6o5LqQnHMi1BEN6yXucgadBRahbRDCHer4YAx5iWXHMhMx/5OL76RA5VVVm/Kgk751Eydw6ovj3pKYUZynmOkpmQ2HrAgMBAAECggEAVJtgHNBIG9XK//AQG9BIIWLrJV3VtGFGgMfNpLdn5tEwHe3nDa5JMZamwjqM6G1OPxM5n2T8jzsZDkLP7yMrdhE4YLCOuKpS9fAsXPVLgufvgD/NBi/maLRqhkyD3ycXwlB8HFLRveToNACDfT1Xu6TBmSg51HBjfkxQtI5WJL9/VD/Pma6qxlLefXHxsGiwIvX/8NFqFJ0IuIVVimTWl329zS+57z06pCsuDKK31U4UTJM65geMwUuw6vH170uMIBWxLS8YDJdTKms669Uk3F/V2FtouFz07dHFi8Krs1vRjYfZ77lsRQTNuYlE/B3XSMKDTDsSxaXYoM6SE9GhuQKBgQDvbbtAVv6rG7iUGBc2djgiOiZjdkyrWTb4cSgoP8pP46EnDK/WXae1auX3I5P5UTmb6p3ksCNNfyBDkkXPNItgFFWcKQnPe5aEMnyxIqBLPDGOpp2337LZwbgCou7cc/shW0uhAgkr0lmuReQwHts34kbE4TKbdGmOaVHqNqr0TQKBgQDabE+KhSapnDpOBSRzl0b+BW1vGRGnXEEhQR5SQcpPGHudtANH6dqPfxx4/96cy7YdygcyPX5MMwB73qvY3+9krBRvRD++jltThl3oLefSOlBcEHsTvzc76jMI5C+7uFqzIyS+gsi5hTv3of6Q9ymyzEtgiA3ehC5AqmJ6NpirFwKBgFBrvjKtRds5c3Ui5mEfslkkyRItgTEoxUML1x411wGghtez9jf9u0A/iMDLTX+33a7WTnSrCSCVq8OmlRY1Iv+BtQO/8RClBXif8Kwa4laDAG5W3rENTWjBHcqc6bhYqKianruVEHmMrRzRUwUqyB1sPrMQpUv7/Rydmase86sdAoGADdFgTtERmxVJEvp8Tdu6IAPT4n1hgobxj9sAwg9rbwmLeHSU6I3Ax+cws+7r9Ftm0Aeh4OnG/acUVsHFeVjhWisQt+FHbxSubmBHvJJ64e/SeaCJSLyGEAJG7D8TTfrhsgd9IZhAfowROR9EbYNVXfxSoG67AeK20lx1Emo1yk0CgYEAyB5sbj1dTmaiv7vABrO1g+jltMISDvai7QeZTFC5XrGAKvgi9E3aNjOJJ1/ODE/pfpnz5PZaOzIsnJYUNJwCtg0mAdPwmgcTVt/YzmxfM8zH5pmppkKQLrpAtEm3MWwx2dnpGoUwO3PvLFXj3n18MCAdDYKi4gEqr7svEYcBb6s=

  smartContractAddress:
    businessData: KT1H7skNUrjgPcMoLjzXkGvBu6DKehsRRzSW
    digitalPassport: KT1JVhi3y73XrEXbd6tiZMAzPfHstW2eGqe8
    digitalPassportProxyTokenController: KT1EhhWaVjCVCgFHvZfMRmb6JwFxj1aopPAL
    organizationYellowPage: KT19DjuQT2MnmdFWKX1TuS28P9NkZNMTK9rt

  tezosApiGatewayUrl: https://tezos-api-gateway.localhost

  traefik:
    log:
      level: DEBUG
  controllers:
    config: true
    traefik: true

  spring:
    profiles:
      active:

keycloak:
  assetOwnerIdentityProviderConfigClientSecret: "860faf20430956489e72b101ad8ca95ba62dff46"
  extraEnvVars:
    - name: REALM
      value: "collaborate"
    - name: ROLE_ATTRIBUTE_KEY
      value: "type"
    - name: ROLE_ATTRIBUTE_VALUE
      value: "collaborate"
    - name: ASSET_OWNER_IDENTITY_PROVIDER_DISPLAY_NAME
      value: "GitHub for vehicle owner"
    - name: ASSET_OWNER_IDENTITY_PROVIDER_CONFIG_CLIENT_ID
      value: "7a62e8890c2b5a57d1d6"
    - name: IDENTITY_BROKER_ENABLED
      value: "true"

tezos-api-gateway:
  vault:
    server:
      debug: true
      dev:
        enabled: true
      standalone:
        enabled: false
    customInitScript: vault write transit/restore/admin backup=eyJwb2xpY3kiOiB7Im5hbWUiOiAiYWRtaW4iLCAia2V5cyI6IHsiMSI6IHsia2V5IjogImxDOU5HYTNBaTlSZEF6cUluTkk0VXBlaG5lVnFpRmpXQyt5eS8yenJPbnJadmJWelNxaEo5c3J0QWRycy9NYzBiVlV4c2I4WUcvSlc2b2RPOG1Pak9BPT0iLCAiaG1hY19rZXkiOiAidkllQ0YvWFFrZWZpdU5YS3RtQktBUVJqTHdia0lpUXl3MjFuOXczcEJBST0iLCAidGltZSI6ICIyMDIxLTA0LTI2VDE0OjAxOjU3LjE4NTM1NDkzNloiLCAiZWNfeCI6IG51bGwsICJlY195IjogbnVsbCwgImVjX2QiOiBudWxsLCAicnNhX2tleSI6IG51bGwsICJwdWJsaWNfa2V5IjogIjJiMjFjMHFvU2ZiSzdRSGE3UHpITkcxVk1iRy9HQnZ5VnVxSFR2Smpvemc9IiwgImNvbnZlcmdlbnRfdmVyc2lvbiI6IDAsICJjcmVhdGlvbl90aW1lIjogMTYxOTQ0NTcxN319LCAiZGVyaXZlZCI6IGZhbHNlLCAia2RmIjogMCwgImNvbnZlcmdlbnRfZW5jcnlwdGlvbiI6IGZhbHNlLCAiZXhwb3J0YWJsZSI6IHRydWUsICJtaW5fZGVjcnlwdGlvbl92ZXJzaW9uIjogMSwgIm1pbl9lbmNyeXB0aW9uX3ZlcnNpb24iOiAwLCAibGF0ZXN0X3ZlcnNpb24iOiAxLCAiYXJjaGl2ZV92ZXJzaW9uIjogMSwgImFyY2hpdmVfbWluX3ZlcnNpb24iOiAwLCAibWluX2F2YWlsYWJsZV92ZXJzaW9uIjogMCwgImRlbGV0aW9uX2FsbG93ZWQiOiBmYWxzZSwgImNvbnZlcmdlbnRfdmVyc2lvbiI6IDAsICJ0eXBlIjogMiwgImJhY2t1cF9pbmZvIjogeyJ0aW1lIjogIjIwMjEtMDQtMjZUMTQ6MDI6MjMuNjg4NTkwNTg4WiIsICJ2ZXJzaW9uIjogMX0sICJyZXN0b3JlX2luZm8iOiBudWxsLCAiYWxsb3dfcGxhaW50ZXh0X2JhY2t1cCI6IHRydWUsICJ2ZXJzaW9uX3RlbXBsYXRlIjogIiIsICJzdG9yYWdlX3ByZWZpeCI6ICIifSwgImFyY2hpdmVkX2tleXMiOiB7ImtleXMiOiBbeyJrZXkiOiBudWxsLCAiaG1hY19rZXkiOiBudWxsLCAidGltZSI6ICIwMDAxLTAxLTAxVDAwOjAwOjAwWiIsICJlY194IjogbnVsbCwgImVjX3kiOiBudWxsLCAiZWNfZCI6IG51bGwsICJyc2Ffa2V5IjogbnVsbCwgInB1YmxpY19rZXkiOiAiIiwgImNvbnZlcmdlbnRfdmVyc2lvbiI6IDAsICJjcmVhdGlvbl90aW1lIjogMH0sIHsia2V5IjogImxDOU5HYTNBaTlSZEF6cUluTkk0VXBlaG5lVnFpRmpXQyt5eS8yenJPbnJadmJWelNxaEo5c3J0QWRycy9NYzBiVlV4c2I4WUcvSlc2b2RPOG1Pak9BPT0iLCAiaG1hY19rZXkiOiAidkllQ0YvWFFrZWZpdU5YS3RtQktBUVJqTHdia0lpUXl3MjFuOXczcEJBST0iLCAidGltZSI6ICIyMDIxLTA0LTI2VDE0OjAxOjU3LjE4NTM1NDkzNloiLCAiZWNfeCI6IG51bGwsICJlY195IjogbnVsbCwgImVjX2QiOiBudWxsLCAicnNhX2tleSI6IG51bGwsICJwdWJsaWNfa2V5IjogIjJiMjFjMHFvU2ZiSzdRSGE3UHpITkcxVk1iRy9HQnZ5VnVxSFR2Smpvemc9IiwgImNvbnZlcmdlbnRfdmVyc2lvbiI6IDAsICJjcmVhdGlvbl90aW1lIjogMTYxOTQ0NTcxN31dfX0K
