{{- if .Values.mail.dev }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "collaborate-dapp.fullname" . }}-maildev
  labels:
    {{- include "collaborate-dapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: maildev
spec:
  selector:
    matchLabels:
      {{- include "collaborate-dapp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: maildev
  template:
    metadata:
      labels:
        {{- include "collaborate-dapp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: maildev
    spec:
      serviceAccountName: {{ include "collaborate-dapp.serviceAccountName" . }}
      containers:
        - name: maildev
          image: "maildev/maildev"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: smtp
              containerPort: 25
              protocol: TCP
{{- end }}
