{{- if .Values.mail.dev }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "collaborate-dapp.fullname" . }}-maildev
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "collaborate-dapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: maildev
spec:
  podSelector:
    matchLabels:
      {{- include "collaborate-dapp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: maildev
  ingress:
    - from:
      - podSelector: {}
{{- end }}
