apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "collaborate-catalog.fullname" . }}-api
  labels:
    {{- include "collaborate-catalog.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "collaborate-catalog.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "collaborate-catalog.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: collaborate-catalog-api
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "{{ .Release.Name }}-{{ .Values.api.rabbitmq.name }}"
            - name: SPRING_RABBITMQ_PORT
              value: {{ .Values.api.rabbitmq.port | quote }}
            - name: SPRING_RABBITMQ_USERNAME
              value: {{ .Values.api.rabbitmq.auth.username | quote }}
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-{{ .Values.api.rabbitmq.name }}"
                  key: rabbitmq-password
            - name: SPRING_DATA_MONGODB_HOST
              value: "{{ .Release.Name }}-{{ .Values.api.mongodb.name }}"
            - name: SPRING_DATA_MONGODB_USERNAME
              value: {{ .Values.api.mongodb.auth.username | quote }}
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-{{ .Values.api.mongodb.name }}"
                  key: mongodb-password
            - name: SPRING_DATA_MONGODB_DATABASE
              value: {{ .Values.api.mongodb.auth.database | quote }}
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "{{ .Values.api.iam.catalog.uri }}/auth"
          ports:
            - name: http
              containerPort: 7773
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
