{{ $name := (include "collaborate-dapp.db.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "collaborate-dapp.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "collaborate-dapp.automaticSecret" (list . $name "password" 20 .Values.db.auth.password) }}
{{- include "collaborate-dapp.automaticSecret" (list . $name "postgres-password" 20 .Values.db.auth.postgresPassword) }}
