kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ (print $.Release.Name "-keycloak") | trunc 20 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "collaborate-dapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
    - from:
      {{- .Values.ingress.from | toYaml | nindent 6 }}
