apiVersion: v1
kind: Secret
metadata:
  name: {{ include "collaborate.keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "collaborate.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := list "admin-password" "management-password" }}
  {{- include "collaborate.automaticSecret" (list . (include "collaborate.keycloak.fullname" .) $keys) | indent 2 }}
