{{- $name := printf "%s-%s" (include "collaborate-dapp.fullname" .) "keycloak-extra-secrets" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "collaborate-dapp.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "collaborate-dapp.automaticSecret" (list . $name "BACKEND_SECRET" 20 .Values.api.secret) }}
{{- if .Values.mail.dev }}
  SMTP_HOST: {{ print (include "collaborate-dapp.fullname" . ) "-maildev" | b64enc | quote }}
  SMTP_PORT: ""
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  SMTP_AUTH: ""
  SMTP_SSL: ""
{{- else }}
  SMTP_HOST: {{ .Values.mail.host | b64enc | quote }}
  SMTP_PORT: {{ .Values.mail.port | b64enc | quote }}
  SMTP_USER: {{ .Values.mail.username | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.mail.password | b64enc | quote }}
  SMTP_AUTH: {{ "true" | b64enc | quote }}
  SMTP_SSL: {{ "true" | b64enc | quote }}
{{- end }}
  {{- if .Values.keycloak.assetOwnerIdentityProviderConfigClientSecret }}
  ASSET_OWNER_IDENTITY_PROVIDER_CONFIG_CLIENT_SECRET: {{ .Values.keycloak.assetOwnerIdentityProviderConfigClientSecret | b64enc | quote }}
  {{- end }}
