apiVersion: v1
kind: Secret
metadata:
  name: {{ include "collaborate.db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "collaborate.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := list "postgresql-password" "postgresql-postgres-password" }}
  {{- include "collaborate.automaticSecret" (list . (include "collaborate.db.fullname" .) $keys) | indent 2 }}
