apiVersion: v1
kind: Service
metadata:
  name: {{ include "collaborate-catalog.fullname" . }}-iam
  labels:
    {{- include "collaborate-catalog.labels" . | nindent 4 }}
    app.kubernetes.io/component: iam
spec:
  type: {{ .Values.iam.service.type }}
  ports:
    - port: {{ .Values.iam.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "collaborate-catalog.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: iam
