name: ci
on:
  push:
    branches:
      - "**"

env:
  FORCE_COLOR: 1

jobs:

  ############################ tests ############################

  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: eniblock/build/actions/setup@develop
      id: setup
      with:
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Run nft tests
      run: |
         earthly --strict ./dapp/api+test

  test-keycloak:
    runs-on: ubuntu-latest
    steps:
    - uses: eniblock/build/actions/setup@develop
      id: setup
      with:
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Run admin tests
      run: |
         earthly --strict ./dapp/iam+test

  lint-helm:
    runs-on: ubuntu-latest
    steps:
    - uses: eniblock/build/actions/setup@develop
      id: setup
      with:
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: |
         earthly --strict \
         ./helm+lint


  ############################ docker ############################

  docker-api:
    runs-on: ubuntu-latest
    needs: [test-api, test-keycloak, lint-helm]
    steps:
    - uses: eniblock/build/actions/setup@develop
      id: setup
      with:
        helmdir: helm/collaborate-dapp
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the asset image
      run: |
         earthly --strict --push ./dapp/api+docker \
         --tag=${{ steps.setup.outputs.tag }}

  docker-keycloak:
    runs-on: ubuntu-latest
    needs: [test-api, test-keycloak, lint-helm]
    steps:
    - uses: eniblock/build/actions/setup@develop
      id: setup
      with:
        helmdir: helm/nft
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the core image
      run: |
         earthly --strict --push ./dapp/iam+docker \
         --tag=${{ steps.setup.outputs.tag }}

  ############################ helm ############################

  helm-publish:
    runs-on: ubuntu-latest
    needs: [docker-api, docker-keycloak]
    steps:
    - uses: eniblock/build/actions/setup@develop
      id: setup
      with:
        helmdir: helm/collaborate-dapp
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build/Publish the helm charts
      run: |
         earthly \
         --secret registry_username=notused \
         --secret registry_password=${{ github.token }} \
         --strict ./helm+publish \
         --tag=${{ steps.setup.outputs.tag }}
