name: ci
on:
  push:
    branches:
      - "**"
    tags:
      - "*"

jobs:

  ############################ tests ############################

  test-api:
    runs-on: [self-hosted]
    steps:
    - uses: eniblock/build/actions/setup@4.0
      id: setup
      with:
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: earthly ./dapp/api+test

  test-keycloak:
    runs-on: [self-hosted]
    steps:
    - uses: eniblock/build/actions/setup@4.0
      id: setup
      with:
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: earthly ./dapp/iam+test

  lint-helm:
    runs-on: [self-hosted]
    steps:
    - uses: eniblock/build/actions/setup@4.0
      id: setup
      with:
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: earthly ./helm+lint


  ############################ docker ############################

  docker-api:
    runs-on: [self-hosted]
    needs: [test-api, test-keycloak, lint-helm]
    steps:
    - uses: eniblock/build/actions/setup@4.0
      id: setup
      with:
        helmdir: helm/collaborate
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the asset image
      run: earthly ./dapp/api+docker --tag=${{ steps.setup.outputs.tag }}

  docker-keycloak:
    runs-on: [self-hosted]
    needs: [test-api, test-keycloak, lint-helm]
    steps:
    - uses: eniblock/build/actions/setup@4.0
      id: setup
      with:
        helmdir: helm/collaborate
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the core image
      run: earthly ./dapp/iam+docker --tag=${{ steps.setup.outputs.tag }}


  ############################ helm ############################

  helm-publish:
    runs-on: [self-hosted]
    needs: [docker-api, docker-keycloak]
    steps:
    - uses: eniblock/build/actions/setup@4.0
      id: setup
      with:
        helmdir: helm/collaborate
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build/Publish the helm charts
      run: |
        earthly \
          --secret registry_username=notused \
          --secret registry_password=${{ github.token }} \
          ./helm+publish \
          --tag=${{ steps.setup.outputs.tag }}
    - name: Generate job summary
      run: |
        cat <<"EOF" >> $GITHUB_STEP_SUMMARY
        ## Helm package
        Helm package was generated with tag `${{ steps.setup.outputs.tag }}`

        Use it directly with

        ~~~bash
        helm install col oci://ghcr.io/eniblock/collaborate --version ${{ steps.setup.outputs.tag }}
        ~~~

        or as a helm dependency in your `Chart.yaml`:

        ~~~yaml
        dependencies:
          - name: collaborate
            version: "${{ steps.setup.outputs.tag }}"
            repository: "oci://ghcr.io/eniblock"
        ~~~
        EOF
